### ISSUE TITLE
Automatizar proceso

### ISSUE THREAD

**Issue by llrs** [civio/covid-vaccination-spain#1]
Viendo que el proceso es sencillo se podria poner una github action que lo haga diariamente. 
Por supuesto quedará la parte de comprobar los resultados para el que siempre se necesitará una persona... 

```
on:
  schedule:
    - "* * * * * " # Setup daily at a convenient hour. 
steps:
- uses: actions/checkout@v2
- uses: actions/setup-ruby@v1
  with:
    ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
- name: download
  run: ./fetch.sh
- name: Parse
  run: ruby parse.rb > data.csv
- name: commit 
  run: ...
```
